options:
  # send all build logs to Cloud Logging (no bucket needed)
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build your Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA'
      - '.'

  # 2) Push the image into Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA'

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy python-service \
          --image gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA \
          --region us-central1 \
          --platform managed \
          --project double-genius-466920-b8 \
          --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA'
