steps:
# 1) Build your Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA'
    - '.'

# 2) Push the image into Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA'

# 3) Deploy that image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy python-service-649439655037 \
        --image gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA \
        --region us-central1 \
        --platform managed \
        --project double-genius-466920-b8 \
        --allow-unauthenticated

# (Optional) Let Cloud Build know which image(s) you produced
images:
  - 'gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA'
