# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ───────────────────────────────
  # 1) Run pytest (with PYTHONPATH)
  - id: run-tests
    name: python:3.10-slim
    entrypoint: bash
    # make sure Python can find main.py
    env:
      - "PYTHONPATH=/workspace"
    args:
      - -c
      - |
        set -e
        pip install --upgrade pip
        pip install -r requirements.txt
        pytest --maxfail=1 --disable-warnings -q

  # ───────────────────────────────
  # 2) Build Docker image
  - id: docker-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA
      - .

  # ───────────────────────────────
  # 3) Push to Container Registry
  - id: docker-push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA

  # ───────────────────────────────
  # 4) Deploy to Cloud Run
  - id: run-deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        gcloud run deploy python-service \
          --image=gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --project=double-genius-466920-b8 \
          --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA
